apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: informationgrid
spec:
  selector:
    app: kafka-connect
  ports:
    - port: 8083
      name: web
      nodePort: 8083
  type: NodePort
