apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: demo
spec:
  releaseName: kafka
  chart:
    spec:
      chart: kafka
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 14.2.5
  interval: 10m
  install:
    remediation:
      retries: 3
  values:
    deleteTopicEnable: true
    externalAccess:
      enabled: true
      service:
        type: NodePort
        nodePorts:
          - 9092
        useHostIPs: true
    zookeeper:
      service:
        type: NodePort
        nodePorts:
          client: 2181