deleteTopicEnable: true
externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts:
      - 9092
    useHostIPs: true
zookeeper:
  service:
    type: NodePort
    nodePorts:
      client: 2181