---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: informationgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
      - env:
        - name: CONFIG_STORAGE_TOPIC
          value: my_connect_configs
        - name: OFFSET_STORAGE_TOPIC
          value: my_connect_offsets
        - name: STATUS_STORAGE_TOPIC
          value: my_connect_statuses
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: 10.211.55.3:9092  
        image: uiterlix/debezium-connect:1.9
        imagePullPolicy: Always
        name: kafka-connect
        ports:
        - containerPort: 8083
          name: connect
          protocol: TCP
      restartPolicy: Always
