apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: informationgrid
spec:
  selector:
    app: mysql-debezium
  ports:
    - port: 3306
      name: web
      nodePort: 3306
  type: NodePort
