apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: demo
spec:
  selector:
    app: sqlserver-debezium
  ports:
    - port: 1433
      name: web
      nodePort: 1433
  type: NodePort
